/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import java.awt.Font;
import java.awt.event.ActionEvent;

/**
 * Metodos realizados:
 * Label - etiqueta (Hola mundo)
 * Botones (Cambiar texto)
 * Botones de dos estados (On/Off)
 * CheckBox (Negrita/Cursiva)
 * RadioButton (Destino: Paises)
 * GroupButton (Destino: Paises)
 * ComboBox (Colores)
 * Text Field (Nombre/Edad)
 * TextArea (Descripcion) Similar al anterior pero permite mas lineas de texto aunque solo la muestra en una sola.
 * @author Admin
 */
public class Ej1 extends javax.swing.JFrame {
    /**
     * Creates new form Ej1
     */
    public Ej1() {
        //Constructor
        initComponents();
        etiqueta1.setText("¡ Hola mundo !");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        etiqueta1 = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();
        btnOnOff = new javax.swing.JToggleButton();
        neg = new javax.swing.JCheckBox();
        curs = new javax.swing.JCheckBox();
        texto2 = new javax.swing.JLabel();
        arg = new javax.swing.JRadioButton();
        peru = new javax.swing.JRadioButton();
        chile = new javax.swing.JRadioButton();
        selec2 = new javax.swing.JButton();
        destino = new javax.swing.JLabel();
        colores = new javax.swing.JComboBox<>();
        txtcolor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomb = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        txtnomb = new javax.swing.JLabel();
        txtedad = new javax.swing.JLabel();
        mostrar = new javax.swing.JButton();
        desc = new javax.swing.JLabel();
        txtdesc = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setSize(new java.awt.Dimension(400, 300));

        etiqueta1.setBackground(new java.awt.Color(51, 153, 255));
        etiqueta1.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        etiqueta1.setForeground(new java.awt.Color(0, 153, 255));
        etiqueta1.setText("Etiqueta de prueba nro.1");
        etiqueta1.setBorder(new javax.swing.border.MatteBorder(null));

        boton1.setText("Boton de prueba nro.1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        btnOnOff.setText("Boton doble ON/OFF");
        btnOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnOffActionPerformed(evt);
            }
        });

        neg.setText("Negrita");
        neg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negActionPerformed(evt);
            }
        });

        curs.setText("Cursiva");
        curs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursActionPerformed(evt);
            }
        });

        texto2.setText("Texto de prueba.");

        buttonGroup1.add(arg);
        arg.setText("Argentina");

        buttonGroup1.add(peru);
        peru.setText("Peru");
        peru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peruActionPerformed(evt);
            }
        });

        buttonGroup1.add(chile);
        chile.setText("Chile");
        chile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chileActionPerformed(evt);
            }
        });

        selec2.setText("Seleccionar");
        selec2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selec2ActionPerformed(evt);
            }
        });

        destino.setText("Destino:");

        colores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Verde", "Amarillo" }));
        colores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloresActionPerformed(evt);
            }
        });

        txtcolor.setText("Color Seleccionado:");

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Edad:");

        nomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombActionPerformed(evt);
            }
        });

        txtnomb.setText("Tu nombre es:");

        txtedad.setText("Tu edad es:");

        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        desc.setText("Descripcion:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtdesc.setViewportView(jTextArea1);

        guardar.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boton1)
                                        .addGap(31, 31, 31)
                                        .addComponent(btnOnOff))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(neg)
                                        .addGap(160, 160, 160)
                                        .addComponent(arg)))
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnomb)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtedad)
                                        .addGap(46, 46, 46)
                                        .addComponent(mostrar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nomb, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(colores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqueta1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(guardar)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(curs)
                                        .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(chile)
                                                .addComponent(peru)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(selec2)
                                            .addGap(93, 93, 93)
                                            .addComponent(desc)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 27, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boton1)
                        .addComponent(btnOnOff)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neg)
                    .addComponent(arg)
                    .addComponent(jLabel2)
                    .addComponent(edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curs)
                    .addComponent(chile)
                    .addComponent(txtnomb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(texto2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peru))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(colores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(selec2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtedad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(desc)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(104, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(mostrar)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guardar)
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // Metodo que realiza al presionar el boton1
        etiqueta1.setText("Boton 1 presionado.");
        
    }//GEN-LAST:event_boton1ActionPerformed

    private void btnOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnOffActionPerformed
        // Metodo del boton ON/OFF
        if (btnOnOff.isSelected()){
            etiqueta1.setText("Boton encendido.");
            btnOnOff.setText("Apagar");
        } else {
            etiqueta1.setText("Boton apagado.");
            btnOnOff.setText("Encender");
        }
    }//GEN-LAST:event_btnOnOffActionPerformed

    private void negActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negActionPerformed
        int i=0;
        if (neg.isSelected()) i+=Font.BOLD;
        if (curs.isSelected()) i+=Font.ITALIC;
        texto2.setFont(new Font ("Dialog", i, 12));
    }//GEN-LAST:event_negActionPerformed

    private void peruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peruActionPerformed

    private void chileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chileActionPerformed

    private void selec2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selec2ActionPerformed
        // Metodo del radio boton seleccionar.
        // NO permite tratar dos (o mas) opciones seleccionadas. 
        // En dicho caso, siempre trata la primer seleccion de la lista.
        // Se soluciona con Button Group
        if (arg.isSelected()) {
            destino.setText("Destino: Argentina.");
        } else if (peru.isSelected()) {
            destino.setText("Destino: Peru.");
        } else if (chile.isSelected()) {
            destino.setText("Destino: Chile.");
        } else {
            destino.setText("Seleccione una opcion.");
        }
    }//GEN-LAST:event_selec2ActionPerformed

    private void cursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursActionPerformed
        int i=0;
        if (neg.isSelected()) i+=Font.BOLD;
        if (curs.isSelected()) i+=Font.ITALIC;
        texto2.setFont(new Font ("Dialog", i, 12));
    }//GEN-LAST:event_cursActionPerformed

    private void coloresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloresActionPerformed
        // Metodo de ComboBox. Desplegable.
        txtcolor.setText("Color seleccionado: "+colores.getSelectedItem());
        
    }//GEN-LAST:event_coloresActionPerformed

    private void nombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // Metodo Text Field:
        String nombre= nomb.getText();
        if (nombre.isEmpty()) {
            txtnomb.setText("Ingrese un nombre.");
        } else {
            txtnomb.setText("Su nombre es: "+nombre);
        }
        String ed= edad.getText();
        if (ed.isEmpty()) {
            txtedad.setText("Ingrese un numero.");
        } else {
            txtedad.setText("Su edad es: "+ed+" años.");
        }
    }//GEN-LAST:event_mostrarActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ej1().setVisible(true);
            }
        });
           
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton arg;
    private javax.swing.JButton boton1;
    private javax.swing.JToggleButton btnOnOff;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chile;
    private javax.swing.JComboBox<String> colores;
    private javax.swing.JCheckBox curs;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel destino;
    private javax.swing.JTextField edad;
    private static javax.swing.JLabel etiqueta1;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mostrar;
    private javax.swing.JCheckBox neg;
    private javax.swing.JTextField nomb;
    private javax.swing.JRadioButton peru;
    private javax.swing.JButton selec2;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel txtcolor;
    private javax.swing.JScrollPane txtdesc;
    private javax.swing.JLabel txtedad;
    private javax.swing.JLabel txtnomb;
    // End of variables declaration//GEN-END:variables
}